jenkins:
  build: .
  mem_limit: 512m
  ports:
   - "80:8080"
   - "50000:50000"
  env_file:
   - ./local.env
slave:
  image: silintl/appbuilder-agent
  mem_limit: 1024m
  links:
    - jenkins:jenkins-master
  command: -master http://jenkins-master:8080
